name: Quality check

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: actions/labeler@v4
        env:
          LABELS: ${{ steps.check_pr_labels.outputs.all-labels }}
      - name: Check Labels back end
        if: contains(github.event.pull_request.labels.*.name, 'Back End API')
        run: |
          echo "Back End API"
      - name: Check Labels front end
        if: contains(github.event.pull_request.labels.*.name, 'Front Web App')
        run: |
          echo "Front Web App"

  build:
    runs-on: ubuntu-latest
    needs: triage

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install:packages
      - run: npm run lint
      - run: echo "🍏 lint is ${{ job.status }}."

  lint-and-test-back-end-api:
    needs: triage
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Back End API') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: apps/back-end-api
      - name: Lint
        run: npm run lint
        working-directory: apps/back-end-api
      - name: Test
        run: npm run test
        working-directory: apps/back-end-api

  lint-and-test-web-app:
    needs: triage
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Front Web App') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: apps/web-app
      - name: Lint
        run: npm run lint
        working-directory: apps/web-app
      - name: Test
        run: npm run test
        working-directory: apps/web-app
