services:
  mobile-app:
    build:
      context: .
      dockerfile: ./docker/mobile-app.Dockerfile
    ports:
      - "8080:80"

  web-app:
    ## Option 1 - Build from Dockerfile
    build:
      context: .
      dockerfile: ./docker/web-app.Dockerfile
    ## Option 2 - Use the latest image available on Docker Hub
    # image: "guillaume60240/ecf-escape-game-web-app:latest"
    ports:
      - "8081:80"

  postgres:
    extends:
      file: ./docker/postgres/docker-compose.yml
      service: postgres
    env_file: ./docker/postgres/postgres.env

  pg-admin:
    depends_on:
      - postgres
    extends:
      file: ./docker/postgres/docker-compose.yml
      service: pg-admin
    env_file: ./docker/postgres/pg-admin.env

  back-end-api:
    ## Option 1 - Build from Dockerfile
    build:
      context: .
      dockerfile: ./docker/back-end-api.Dockerfile
    ## Option 2 - Use the latest image available on Docker Hub
    # image: "guillaume60240/ecf-escape-game-back-end-api:latest"
    ports:
      - "8082:3000"
    env_file:
      - ./apps/back-end-api/.env.dist
    depends_on:
      - postgres
