services:
  mobile-app:
    build:
      context: .
      dockerfile: ./docker/mobile-app.Dockerfile
    ports:
      - "8080:80"
  web-app:
    build:
      context: .
      dockerfile: ./docker/web-app.Dockerfile
    ports:
      - "8081:80"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./apps/back-end-api/.env.dist
      
  back-end-api:
    build:
      context: .
      dockerfile: ./docker/back-end-api.Dockerfile
    ports:
      - "8082:80"
    env_file:
      - ./apps/back-end-api/.env.dist
    depends_on:
      - postgres